version: "3.7"

services:
  postgres:
#    image: postgres:12.6
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: admin
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "test"
  api:
    container_name: rad_cars
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /rad_cars
    command: python manage.py migrate
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/rad_cars
    ports:
      - '8000:8000'
    expose:
      - '8000'
    links:
      - postgres
    depends_on:
      - postgres
