# Generated by Django 4.2 on 2023-06-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.provider'),
        ),
    ]
