# Generated by Django 4.2 on 2023-06-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quotation_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.provider'),
        ),
    ]
